### ISSUE TITLE
Missing reference of CaptureManagerLibrary in project CaptureManagerToCSharpProxy

### ISSUE THREAD

**Issue by phamviethuy** [Xirexel/CaptureManagerSDK#13]
Where I can find "CaptureManagerLibrary" in project CaptureManagerToCSharpProxy.
I want to use SDK in .net 6.
Thank you!
![image](https://user-images.githubusercontent.com/42407610/199809132-76524d6a-6c8e-4bf3-b31a-67ed66c29647.png)

**Comment by laheller** [comment]
@phamviethuy 

You can fix it by downloading [CaptureManagerSDK-1.21.0-Freeware](https://www.codeproject.com/KB/Articles/1017223/CaptureManagerSDK-1.21.0-Freeware.zip) unpacking it to any directory where you run either:
`regsvr32 x64\CaptureManager.dll`
or
`regsvr32 x86\CaptureManager.dll`

Finally reload the Visual Studio project.
